### ISSUE TITLE
Restaurant: Dos Palillos

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#1]
By the ex Chef de Cuisine at El Bulli.

[http://www.dospalillos.com/home.php?rest=2&lang=en](http://www.dospalillos.com/home.php?rest=2&lang=en)

@dylanegan @codenamejac

**Comment by dylanegan** [comment]
LET'S DO IT!

**Comment by lstoll** [comment]
Brought up on the mailing list. Will book when we have some numbers.

**Comment by lstoll** [comment]
So @sr proposes tonight.

**Comment by lstoll** [comment]
At the restaurant with @codenamejac, @dylanegan, @sr, @danishkhan and @jeshuaborges. Waiting for @brianmario and Theresa.

**Comment by lstoll** [comment]
So far it's amazing, which is unfortunate for @mtodd @rsanheim

**Comment by lstoll** [comment]
Nailed that.

**Comment by dylanegan** [comment]
TOTALLY WINNING! http://www.youtube.com/watch?v=bmpONxJ7JSw
