### ISSUE TITLE
Shooting

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#10]
@stolt45 @kch @mattmanning @wuputah @atmos @codenamejac @benburkert @tsykoduk

Let's go shoot guns in SF, week beginning 23 Jul. Any day in particular better for people?

**Comment by atmos** [comment]
:moneybag:, I'm in.

**Comment by tsykoduk** [comment]
There is a meetup at heroku tuesday, and I am planning on attending. Other then that, let's dooo it.

**Comment by mattmanning** [comment]
I'm in too.

**Comment by kch** [comment]
I can be in but I still wanted to do the go-kart thing.

**Comment by benburkert** [comment]
:gun: :+1: :metal:

**Comment by mattmanning** [comment]
I'm also super down for go karts. I'd actually do that instead of shooting if it came down to it.

**Comment by dylanegan** [comment]
:gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun: :gun:

Please film this for animated GIF purposes.

**Comment by wuputah** [comment]
Bring your favorite gun!
http://www.tsa.gov/travelers/airtravel/assistant/editorial_1188.shtm
http://www.tsa.gov/travelers/airtravel/assistant/editorial_1666.shtm
http://oag.ca.gov/firearms/travel

Or: let's go trap shooting. :bird: :gun:

**Comment by stolt45** [comment]
I'm hoping we can do both.

1) go shooting
2) go go carting

I was going to try to surprise you guys but since you all will self organize this if I don't say something I'm lettin' ya'all know.

**Comment by lstoll** [comment]
![](http://fireden.net/wp-content/uploads/2012/05/why_not_both.png)

When were you thinking of karting?

**Comment by lstoll** [comment]
So this didn't happen.

But I'll be back end of Nov. Closing for now.
