### ISSUE TITLE
Singapore F1 GP

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#11]
Is on 21-23 Sep. I'm thinking about arriving on the Thurs (20th) afternoon, flying out Mon (24th) evening. Looks like tickets are about AU$600, accomodation for 4 nights in a basic place about the same.

@benschwarz @dylanegan

**Comment by lstoll** [comment]
I'm thinking about the 'Padang Combination' - [Ticket Info Here](http://www.singaporegp.sg/ticket/ticket_price.php), thoughts? I don't want to spend all of my time at the F1, I'd like to come and go and hang out in .sg as well.

Dylan - I assume you don't want to F1?

The GP is in the [Marina/Esplanade](https://maps.google.com/maps?q=Esplanade+Singapore&hl=en&ll=1.289926,103.855991&spn=0.02866,0.045276&sll=1.292801,103.84994&sspn=0.02866,0.045276&oq=Esplan,+Singapore&hq=Esplanade+Singapore&radius=15000&t=m&z=15) area - so accommodation should be around here. I've been looking on booking.com, might check airbnb

If we're interested I'd suggest we move on this ASAP - being F1 weekend, accommodation is likely to go quickly.

**Comment by benschwarz** [comment]
Will check it out later.
On Aug 5, 2012 1:16 PM, "Lincoln Stoll" <
reply@reply.github.com>
wrote:

**Comment by dylanegan** [comment]
I don't think I can do this as it is hard for me to get a flight with points going via Singapore. I might just head to Sydney earlier.

**Comment by lstoll** [comment]
Nailed this.
