### ISSUE TITLE
AT/CH/FR/NL mini-adventure

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#12]
With @codenamejac . Adventurin'

**Comment by lstoll** [comment]
Thinking an overview like this.

![](http://sk.lds.li/Berlin%2C_Germany_to_Berlin%2C_Germany_-_Google_Maps-20121018-125228.jpg)

Berlin/Munich/Switzerland Via Car, then probably Paris/AMS/Berlin via Train. Logistics of ditching the car might be hard.

**Comment by lstoll** [comment]
Driving times:

Berlin -> München: ~6h
München -> Innsbruck -> Scuol -> St. Moritz: ~4h15m
**Option 1** - More mountains etc to Zürich
St. Moritz -> St Gotthard -> Zürich: ~4h15m
Zürich -> Lörrach: ~1hr
**Option 2** - Rheintal, drop car in Lindau
_This could also be tacked on to above, avoiding night in St. Moritz_
St. Moritz -> Lindau: ~2h15m
Lindau -> Zürich (Train), 1h45-2h30

Train times:

Zurich -> Paris: 4h. CHF115 "Special Offer"
Paris -> Amsterdam: 3h15. €129 "Best Price"
Amsterdam -> Berlin: 6h, €35->€60

**Comment by lstoll** [comment]
Considered itinerary

**Day 1** Drive Berlin -> Munich, night in/near Munich (Preferably in, go out at night)
**Day 2** Drive Munich -> Lindau via Alps. Spend night in Zurich.
**Day 3** Afternoon train to Paris.
**Day 4** In Paris
**Day 5** Afternoon train to Amsterdam
**Day 6** In Amsterdam
**Day 7** Afternoon train to Berlin

Considered variation - Night in St. Moritz, gives more day time in Zürich plus breaks drive up a bit (otherwise 6.5-7hrs driving, plus 2hrs train - late arrival in Zürich. St. Moritz is cold and pricy though.

Paris may be better over w/e, Accomodation seemed more forthcoming.

So that makes departure either a wed or thur, and return on a wed.

**Comment by lstoll** [comment]
Car rental for 2+ days is €120 (Golf)

Allow €100/day for accom.

Transport: €120+€150(fuel)+50+200+250+100 = €870
Accom 7 nights at ~€100/night = €700

~€1570

**Comment by sr** [comment]
Kinda :cry: you aren't stopping in my hood

**Comment by lstoll** [comment]
@sr : Still not ruled out - but the train is the same price to Brussels as it is to Amsterdam, and it's already a pricy trip.

I'm going to check it out tonight though, maybe we can get Brussels to Amsterdam cheap. Will you be around the week 29 oct?

**Comment by lstoll** [comment]
This shit [is BOOKED](https://www.tripit.com/trip/public/id/9A9A5B376066)

@sr So we'll be in Brussels on the 29th for a night. Yeahhhh!

**Comment by dylanegan** [comment]
[Bruxelles](https://github.com/dylanegan/travel/blob/master/Belgium/Bruxelles.md), especially [De La Vigne A L'assiette](http://sites.resto.com/delavignealassiette/).

**Comment by sr** [comment]
Hell yes @lstoll.

Was gonna say La Vigne for dinner but they're close on Monday unfortunately. We could do launch there on Tuesday around 11:30AM. That's plenty of time to catch your 1:52 :train2: to Amsterdam.

I'll think of something else for dinner on Monday. There's plenty of choices.

**Comment by lstoll** [comment]
@sr sounds good. Nothing too fancy on Monday, don't wanna spend to much

**Comment by lstoll** [comment]
Will drop in on @stuinzuri in Zürich. Staying in a hotel there, but definitely need to do dinner/drinks somewhere.

**Comment by stuinzuri** [comment]
Supi. See  you next week!

**Comment by lstoll** [comment]
DONE.
