### ISSUE TITLE
Food at Reinstoff

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#13]
http://www.reinstoff.eu/welcome.html

2\* restaurant, out of the 3 in Berlin seems to have a more local twist. Would want to do the "Quite Near" menu (http://www.reinstoff.eu/welcome.html)

/cc @codenamejac @dylanegan

**Comment by lstoll** [comment]
Thinking Tues/Wed, 6-7 Nov.

**Comment by dylanegan** [comment]
That is the five course one? I might be able to do that. I assume this means no Malmö (I'm out of that).

**Comment by lstoll** [comment]
Yeah, pretty :-1: on Mälmo. Be cool to go, but already doing so much travel it'd be nice to hang in Berlin.

I think they come in variable courses, but I could go for the smaller/cheaper one.

**Comment by dylanegan** [comment]
OK. Let me see how :secret: goes and then I'll let you know.

**Comment by lstoll** [comment]
Maybe early Jan, before we head away for a bit?

**Comment by dylanegan** [comment]
@lstoll yeah, let's do it as a farewell dinner. :wink:

**Comment by lstoll** [comment]
Probably 10th Jan, I leave on 12th.

@norbert interested?

**Comment by norbert** [comment]
@lstoll yeah! Better reserve soon.

**Comment by lstoll** [comment]
OK, we're booked in at 1900 on 10 Jan. 4 People.

![](http://sk.lds.li/OpenTable-20121213-120416.jpg)

**Comment by lstoll** [comment]
@dylanegan aah shit, just noticed Kat gets here on that day. Should I move to the day before, or extend the booking?

**Comment by lstoll** [comment]
OK, this is now on the 9th at 1930.

![](http://sk.lds.li/OpenTable-20121213-141323.jpg)

**Comment by lstoll** [comment]
:wine_glass: :wine_glass: nailed it
