### ISSUE TITLE
Australia, Feb 2012

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#14]
So RubyConf is on, and @rkh , @wfarr and @razic (?) should be over for that. Plus @rodjek isn't far.

Maybe we should look at some awesome things to do while everyone is out. Thoughts?

**Comment by rkh** [comment]
+1

**Comment by lstoll** [comment]
Should probably pull @benschwarz in on this, because he's always up for adventures.

**Comment by benschwarz** [comment]
I love adventures as much as I love juice… and I fucking love juice.

**Comment by wfarr** [comment]
I dig this. I think @alanjrogers lives in Melbourne as well.

Also let's get @dylanegan up in hurr.

**Comment by lstoll** [comment]
Yep @alanjrogers lives in Mel, so he'd definitely be up for stuff I'm sure. We should probably do a drinkup at the conf.

@dylanegan won't be in Aus though.

**Comment by rodjek** [comment]
:+1: The Melbourne-ness is unfortunate, but I'll risk the trip south for adventures with you fine people.

**Comment by rodjek** [comment]
by the by, the jasper hotel (where rubyconf is) is a really good hotel

**Comment by benschwarz** [comment]
Clearly, because I live here—I know very little of the quality of local hotels. 
The westin is baller. Thats because its baller everywhere… but so is the price.

**Comment by rodjek** [comment]
Yeah, the Westin is awesome (and has a nice cocktail lounge) but at ~$300/night it is also about twice the price of Jasper :)

**Comment by lstoll** [comment]
I'd suggest AirBnB. There's a bunch of decent, reasonably priced stuff in there - hotels are mega expensive.

**Comment by rkh** [comment]
When will every one be there? I might be interested in an airbnb. Though I have a super limited budget. :(

**Comment by lstoll** [comment]
I'm there from 22 Jan until 21 April :)

@rkh how long are you thinking about being out?

**Comment by lstoll** [comment]
OK, So i've pretty much secured a family house in [Fingal Head, NSW](https://maps.google.com/maps?q=Fingal+Head,+NSW&hl=en&ll=-28.201557,153.566895&spn=1.043241,1.170044&sll=51.175806,10.454119&sspn=11.884806,18.720703&hnear=Fingal+Head+New+South+Wales,+Australia&t=m&z=10) for the week after RubyConf.

It's a nice house in a cool little town, about 40 mins drive from Byron Bay and just south of the Gold Coast. I'm planning on flying up there for a week after the conference to hack and relax, beachside Australian style. Flights to Coolangatta from Melbourne are about $200, and probably less from Sydney. Accomodation is pretty much free (may need to pay a cleaner, and buy me beer). There's no DSL, but we can do a few Telstra MiFi's, or just Railscamp style.

I'd be interested in making this a cool hack house/relaxing in coastal Australia kind of thing, with some small daytrips to nice parts of Oz.

Would anyone be keen?
- @alanjrogers @dgoodlad

**Comment by benschwarz** [comment]
In!

**Comment by rkh** [comment]
+1

**Comment by lstoll** [comment]
Cool, @rkh and I leave the airbnb on the 23rd, so probably catch a party plane after hungover (Fitzroy) lunch on that saturday. I can get 4 of us in for lounge + party seats on plane.

**Comment by dgoodlad** [comment]
Yes!

**Comment by dgoodlad** [comment]
I'd be in for party plane on the 23rd, and can get one more into the lounge.

Looks like there's a $85 flight around 3pm on the 23rd

**Comment by razic** [comment]
@lstoll is there enough room for me as well? what airport would i need to fly into?

**Comment by lstoll** [comment]
DJ749, that's what I was planning. @benschwarz has confirmed that, are you OK with that flight? Just need to check in with @rkh and I should have a booking together, do you mind if I just buy that one? that way we can cab/lounge/hold hands on that one.

**Comment by lstoll** [comment]
@razic depends on what your accommodation requirements are, but totally. Would likely be couch/bed in shared room? Need to fly to OOL, which is easy. We may need to rent a second car to carry us around, but should be pretty cheap. Let's wait for the last few to confirm, and make this shit happen :)

**Comment by lstoll** [comment]
Also @sr

**Comment by lstoll** [comment]
FWIW In the place there are 3 double bedrooms, big living area, then an open loft-y area with some mattresses and stuff. So we should be able to fit as many as needed.

**Comment by razic** [comment]
What are the dates?

**Comment by lstoll** [comment]
Say 23/Feb -> 2 Mar, but flexible in between.

**Comment by rodjek** [comment]
> Also @sr

Is Australia ready for that? ;)

@lstoll count me in for beach hacking if there's a free couch

**Comment by dgoodlad** [comment]
@lstoll DJ749 on Feb 23 would work for me! Not 100% sure I can do the whole week but will definitely be in for the Saturday flight.

**Comment by wfarr** [comment]
Me also.

**Comment by lstoll** [comment]
Sweeeeeet. So I think there will need to be some couch/loft sharage, but we can work that out.

I'm tentatively looking at 23 Feb -> 2 March

So who is planning on what dates, and flying from where? So we can organise any needed rental cars/party planes, and I can confirm with my Uncle that those dates are 100% cool

Also, we'll probably need more that one MiFi, or maybe it's worth just connecting DSL if it's cheap enough with internode/whatever.

**Comment by lstoll** [comment]
@benschwarz and @rkh are exempt from that request, already spoke to those guys.

**Comment by benschwarz** [comment]
I'm good to go in for whatever we end up doing mifi wise.

**Comment by lstoll** [comment]
I already have 1 telstra one. I guess for the most part people can tether, and the out-of-countriers can deal with it? But we'll sort that out when it gets closer, it's just a logistics thing.

**Comment by rodjek** [comment]
I've got a mifi that I can chuck a sim into for foreigners to use

**Comment by wfarr** [comment]
I'm probably just gonna do the intntl roaming with AT&T and tether up.

@lstoll @rodjek want to get a more firm timeline going when we're all in a
room together in a few weeks?

I'll need to do some heavy planning re my flights on account of the conf
and whatnot

**Comment by benschwarz** [comment]
That'll probably cost about a million dollars.
Telstra have sims available here in Australia for about $20, then we can throw data on it. 

We'll sort out the data problem, don't worry about tether (apart from phone calls, of course)

**Comment by dgoodlad** [comment]
Telstra sell sims for $2 now, and data is reasonably priced, don't bother with roaming

**Comment by lstoll** [comment]
@wfarr fuck roaming for tethering. We can hook you up with a cheap oz sim that'll do all your data and tethering shit.

But :+1: for having a quick planning session at summit for @rodjek, @wfarr and @razic

**Comment by lstoll** [comment]
So @dgoodlad @benschwarz @rkh and I have our flights + car, because we already have in town sorted.

Will chat to you others at Summit.

**Comment by razic** [comment]
I'm going to have to pass up this opportunity... sorry guys. Round-trip from HKT to OOL is about $1300 USD and a 17 hour flight. I could get GitHub to pay using my one conference a year benefit but I'd rather use that on something else.

Take lots of pictures and make me jealous :smile:

**Comment by lstoll** [comment]
@razic I thought you were going to be at RubyConf.au?

Also that's a shit routing anyway!

**Comment by alanjrogers** [comment]
I'm in for this too, what flight should I get on?

**Comment by dgoodlad** [comment]
@alanjrogers @lstoll booked us on DJ749 on Feb 23

**Comment by razic** [comment]
@lstoll I was going to go but I'm not a speaker so I have no obligation.

**Comment by alanjrogers** [comment]
@dgoodlad and what flight back? I'll try and get on the same one.

**Comment by dgoodlad** [comment]
I haven't booked a return flight yet, but likely on the Friday for me

**Comment by alanjrogers** [comment]
:boom: :camel: Booked on DJ749 on Feb 23

**Comment by dgoodlad** [comment]
Boom. I'm looking at DJ734 on Mar 1 – 11am on the Friday to make it back for retro that afternoon.

@alanjrogers @lstoll @benschwarz you guys planning to stick around until the Saturday?

**Comment by alanjrogers** [comment]
Unfortunately, I'm very likely going to have to bail on this trip. We've just figured out that we'll be needing to move house around the 7th of March, so the weekends leading up to that will be house hunting and packing.

I've cancelled my flight for the moment, but if things firm up and I can make it after all, I'll book another flight.

:crying_cat_face: :metal:

**Comment by lstoll** [comment]
OK, so here's the current wrap-up for the hack house.

We have 6 people coming: @lstoll, @benschwarz, @rkh, @dgoodlad, @wfarr and @rodjek

@lstoll, @benschwarz, @dgoodlad and @rkh arrive on Sat, Feb 23 at 1610 on VA749, in tool Coolangatta/Gold Coast (OOL)

Everyone has varying leaving times, but we want to be out by early afternoon (1300-1400ish) on Friday, March 1.

The house has 3 bedrooms with double beds/2 bathrooms, a loungeroom (duh), and an open upstairs loft area. It's going to be a tight fit, but it's doable.

Also remember, there's no internet so you'll want local SIMs and copies of fat repos and stuff that you'll want to work with. I also think we'll nail the local Telstra tower, so I'll try and bring a vodafone mifi as backup or something.

Lastly, @wfarr / @rodjek you might want a car. I've organised one for the first crew (doing a roadtrip to MEL after with @benschwarz). We can totally pick you up, but if we want to actually go anywhere as a group we're not going to fit. And we'll probably want to go somewhere, because there's not much in the town we're staying.

**Comment by lstoll** [comment]
Also, I'll probably get a cleaner in afterwards, but we should keep the place decent anyway. Not sure what that'll cost, but won't be too much. I'll sort out the ancilliary bits like that this weekend.

We'll be staying at [Fingal Head](https://maps.google.com/maps?q=Fingal+Head+NSW,+Australia&hl=en&ll=-28.20065,153.565865&spn=0.128441,0.180759&sll=-28.255854,153.575821&sspn=0.128374,0.180759&oq=Fingal+Hea&hnear=Fingal+Head+New+South+Wales,+Australia&t=m&z=13)

Weather will be warm and humid-ish:

![](http://sk.lds.li/TripIt_%7C_A_trip_to_Fingal%2C_Australia_from_February_-_March_2013-20130205-112929.jpg)

so pack appropriately. @rkh - you probably won't want socks with your sandals, and maybe @benschwarz should buy some thongs. I know @wfarr wears shorts permanently anyway, so he's good.

The one venue we can eat at within walking distance is [The Sheoak Shack](http://www.sheoakshack.com/sheoakshack/Cafe.html). It's pretty cool to hang out in. Well, there is a kiosk at a caravan park for dirty burgers and chips too, in case one ends up with a hangover. Otherwise, [Kingscliff](https://maps.google.com/maps?q=Kingscliff,+New+South+Wales,+Australia&hl=en&ll=-28.255854,153.575821&spn=0.128374,0.180759&sll=51.175806,10.454119&sspn=11.703504,23.137207&oq=Kingscliff,+&hnear=Kingscliff+New+South+Wales,+Australia&t=m&z=13) has a set of shops/cafes etc.

We're also a [~40 Minute drive from Byron Bay](https://maps.google.com/maps?saddr=Fingal+Head+NSW,+Australia&daddr=Byron+Bay+NSW,+Australia&hl=en&sll=-28.20065,153.565865&sspn=0.128441,0.180759&geocode=Ff6wUf4dhDonCSnD5Zrk6v-QazHAL0SQtAkGBQ%3BFb7sSv4dW_AnCSkrdj4thWKQazHQ8kOQtAkGBA&oq=Byron&mra=ls&t=m&z=11), so I'd suggest we visit that too.

We can also head north to the Gold Coast, but yeah. It's the Gold Coast.

**Comment by dgoodlad** [comment]
Sounds like I should pack a pillow & sleeping bag just in case!

Is anyone heading to the OOL airport afterwards? Would be good to grab a flight around the same time. I'm bailing on the idea of making it back to MEL for retro on Friday, so whenever...

**Comment by lstoll** [comment]
@dgoodlad that's probably not the worst idea. There should be bedding and stuff, but it'd be safe to bring some if you have some.

I know @rkh is doing that journey, but I can't remember the exactly flight. I think it's VA738 (1355->1715), but I guess he can chime in with that one. That'd probably be the best party plane for MEL.

**Comment by rkh** [comment]
Yep, it's the 1355 one. DJ738.

**Comment by dylanegan** [comment]
Does anyone not have a flight for this trip? I need someone to fly under my name in Australia for four sectors so I am happy to pay for their flight if it is a good price.

**Comment by lstoll** [comment]
@dylanegan not sure how that will go, I think @dgoodlad has checked bags. They have to be carry on only.

**Comment by dylanegan** [comment]
Oh yeah, I should've added that.

**Comment by dgoodlad** [comment]
Yeah I'll have checked bags if I haul sleeping gear with me, sorry @dylanegan !

**Comment by lstoll** [comment]
I think we won at this.
