### ISSUE TITLE
LaConf + Dylan's Birthday

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#15]
So [LaConf](http://la-conf.org) is on early May, in Paris. It's also @dylanegan 's birthday. Should we a) go to the conf and b) part for dylan's birthday.

@dylanegan @sr

**Comment by lstoll** [comment]
So I checked the conference hotel, starts at €959/night. Maybe not there. We could AirBnB.

**Comment by sr** [comment]
Too bad it's in Paris. I heard @keavy is speaking though.

**Comment by lstoll** [comment]
It's like 2hrs on the train from Bruxelles, you can

![](http://assets0.ordienetworks.com/images/GifGuide/DealWithIt/ferrisdealwithit.gif)

 @topfunky will be there too.

**Comment by sr** [comment]
But meeeeeeh it's Pariiiisssssssssss. Although apparently it's gotten better in recent years? I should probably go back.

![](http://gifs.gifbin.com/062012/1338914782_biker_highvives_cop.gif)

**Comment by dylanegan** [comment]
@sr for me bro. FOR ME!

**Comment by lstoll** [comment]
The _event in Berlin which I probably can't name yet_ is from May 10-12, so that's probably going to conflict with the Paris trip.
- @thedukeofsf

**Comment by jeniferduke** [comment]
@lstoll - what are the dates for the Paris conf?

**Comment by lstoll** [comment]
9-10 May, it's [La Conf](http://2013.la-conf.org) . It's a ruby event, so don't think there would be too much overlap in attendees.

**Comment by jeniferduke** [comment]
Oh ok. May 11 and 12th are more important anyway I think for the GitTogether Berlin.

**Comment by lstoll** [comment]
So fuck a color La Conf, but there's some other stuff.
