### ISSUE TITLE
Return to Europe 2012.

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#16]
Because people don't believe me, I'm just going to book this.

@dylanegan @roidrage @rkh @svenfuchs @sr

**Comment by rkh** [comment]
![](http://replygif.net/i/967)

**Comment by dylanegan** [comment]
It's not that we don't believe. It's that we'll just miss you.

![](http://i.imgur.com/q2988.gif)

Yes, that GIF is completely unrelated.

**Comment by sr** [comment]
![](http://forgifs.com/gallery/d/189782-1/Spiderman_propeller.gif)

**Comment by lstoll** [comment]
CONFIRMED. Nailed that one quickly.

![](http://sk.lds.li/Inbox_%2823078_messages%2C_51_unread%29-20121212-180001.jpg)

**Comment by sr** [comment]
![](http://f.cl.ly/items/3v0m1Y3R0X2d1v1d3x0j/animated.gif)

**Comment by rkh** [comment]
That has been photoshopped…

**Comment by lstoll** [comment]
Yeah, I removed the passport and confirmation number so y'all don't fuck with it.
