### ISSUE TITLE
First night in Aus (22 Jan)

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#17]
So Iand at like 1030am. Need somewhere to hang for the day, work out where I'm going to stay that night, then need to drink birds of margarita and reminisce with @benschwarz.

So, can I hang out at the league @benschwarz @joho @geelen ?

**Comment by lstoll** [comment]
Not sure if that pinged @geelen, because I fucked up his GitHub name.

**Comment by joho** [comment]
You're always welcome at the league, come hang.

We've got a spare bed/bedroom out in brunswick if you need somewhere to crash.

**Comment by geelen** [comment]
+1

**Comment by lstoll** [comment]
@dgoodlad likes to drink.

**Comment by lstoll** [comment]
Also cheers guys, will totally swing by as soon as I get in. @alanjrogers is on the same flight too, so maybe drag him down too and lunch.

**Comment by dgoodlad** [comment]
I am, as you mentioned, a fan of alcoholic beverages.

**Comment by lstoll** [comment]
Pretty sure we got drunk.
