### ISSUE TITLE
RailsBerry accom/transport

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#18]
So @dylanegan, airbnb a place? Just the two of us? Seems to be a bunch of one bedroom joints with a sofa bed for ~€35/night.

Also need to get back to Berlin afterwards, maybe via Prague if that goes down (and you have time pre tropisch)

**Comment by dylanegan** [comment]
I acquired a ticket so I'll be going for sure now. Let's lock down some accommodation.

**Comment by lstoll** [comment]
I feel like I might have to drop railsberry, Jac arrives on the 23rd and I have a visa appointment.

**Comment by lstoll** [comment]
Plus, LOT have now changed the fucking time, dicks.

![](http://sk.lds.li/LOT__reservation_20130311_212745.png)

**Comment by dylanegan** [comment]
I get that a LOT.

**Comment by lstoll** [comment]
:laughing: you so punny.
