### ISSUE TITLE
Summit roadtrip

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#19]
Want to drive somewhere. Thinking 19/20 (Sat/Sun after summit), I fly at like 1930 Sun.

@sr @benburkert

**Comment by lstoll** [comment]
$160/day for a Corvette. Or that convertible volvo is  $130.

Where to go?

**Comment by sr** [comment]
Santa Barbara. I'll know for sure on Monday whether I can get a driver license in time for this.

/cc @mtodd

**Comment by mtodd** [comment]
We had talked about road tripping from Nasville to SF for the Summit //cc
@skalnik @vinbarnes @rick @ymendel

On Saturday, December 15, 2012, Simon Rozet wrote:

> Santa Barbara. I'll know for sure on Monday whether I can get a driver
> license in time for this.
> 
> /cc @mtodd https://github.com/mtodd
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lstoll/travel/issues/19#issuecomment-11405685.

## 

Matt Todd
GitHub, Inc
www.github.com
cell: 404-314-2612
blog: maraby.org

**Comment by ymendel** [comment]
We talked about what?

**Comment by rick** [comment]
We had.  I think we had come down to the only sane way to do it was an RV, and there was some prep work that had to be done for that.  The "deadline" for summit hotel arrangements came pretty early and Kevin and I decided we probably wouldn't end up doing the work to get the RV going, so we're just flying out instead. :-/

**Comment by lstoll** [comment]
OK, Santa Barbara is about 7 hours down the 1. Long, but doable return in 2 days. I have to fly out at like 1900 Sun Night with @alanjrogers.

I guess this depends on what happens Friday night.. Could possibly even leave then and spend a night in Santa Cruz or something?

![San Francisco CA to Santa Barbara CA - Google Maps](https://f.cloud.github.com/assets/694/15603/69f4bed2-4799-11e2-9370-c4489a270e41.jpg)

**Comment by alanjrogers** [comment]
I'm down for a road trip too (if there's room of course )

**Comment by lstoll** [comment]
Depends on who's coming and car choices, but it's totally open - we can always convoy it.

**Comment by ymendel** [comment]
![](http://4.bp.blogspot.com/-tivb46dL0M8/UK6E2HoASzI/AAAAAAAAAgc/-6uhH1Pi1pg/s1600/convoy1.jpg)

**Comment by lstoll** [comment]
@ymendel holy shit, that's pretty much exactly what I had in mind.

**Comment by lstoll** [comment]
I think that's @sr on the right, holding on to me. They have matching fro's.

**Comment by lstoll** [comment]
@sr did you get a license?

**Comment by sr** [comment]
@lstoll Nope. Couldn't get an appointment to take the exam early enough. I did get two speeding tickets though.

I think I might bail, being on the 1 and not driving is going to drive me nuts.

**Comment by lstoll** [comment]
Fuck it, convertible corvette rented anyway. 1730 on 18th -> 1730->20th.

**Comment by sr** [comment]
Word, I was just watching Scrubs and got over it somehow. Count me back in. Been researching Santa Barbara a bit. You down for wine tour?

**Comment by lstoll** [comment]
Wine tour sounds good. So you gonna be my passenger now?

**Comment by sr** [comment]
I'd love to be the obnoxious drunk sitting next to you yeah :cocktail::heart_eyes:

**Comment by sr** [comment]
Also there's a Bieber on your face.

**Comment by lstoll** [comment]
Sweet, it's on. Maybe we should haul down to Santa Cruz or something Fri night, then go from there?

**Comment by lstoll** [comment]
Also there's french on your face.

**Comment by mtodd** [comment]
2 seater?

On Saturday, December 22, 2012, Lincoln Stoll wrote:

> Fuck it, convertible corvette rented anyway. 1730 on 18th -> 1730->20th.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lstoll/travel/issues/19#issuecomment-11641959.

## 

Matt Todd
GitHub, Inc
www.github.com
cell: 404-314-2612
blog: maraby.org

**Comment by lstoll** [comment]
All of them are? There's always a Volvo C70 that will fit 4 (comfort in the back can suck, but I drive so I don't care ;), or you could rent a second corvette with someone else who wants to go?

**Comment by mtodd** [comment]
:-1: nahhhhhhhhh

On Sunday, December 23, 2012, Lincoln Stoll wrote:

> All of them are? There's always a Volvo C70 that will fit 4 (comfort in
> the back can suck, but I drive so I don't care ;), or you could rent a
> second corvette with someone else who wants to go?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lstoll/travel/issues/19#issuecomment-11651559.

## 

Matt Todd
GitHub, Inc
www.github.com
cell: 404-314-2612
blog: maraby.org

**Comment by sr** [comment]
@lstoll 

> Maybe we should haul down to Santa Cruz or something Fri night, then go from there?

:+1: 7 hours drive at night sounds like :poop:

Jesus I have about a billion tabs open for shit to do in Santa Barabara.

![](http://s-ak.buzzfed.com/static/imagebuzz/web03/2010/4/11/23/oh-jesus-29170-1271042197-38.jpg)

**Comment by sr** [comment]
@mtodd What does that mean?

**Comment by lstoll** [comment]
Sweet. I'm sure we can find somewhere cheap to stay in Santa Cruz/Monterey, and go to a local restaurant/bar. Then cruise down the 1 to Santa Barbara. Then on Sunday the 1/I-5 depending on time.

When do you fly out from SF?

**Comment by sr** [comment]
Monday afternoon.

**Comment by lstoll** [comment]
what time? I wonder if I could defer my flight a day, that'd give us more time.

**Comment by benburkert** [comment]
yeah, you're gonna wanna drive down HW 1 durring the day. It's an awesome drive during the day but sucks at night.

**Comment by lstoll** [comment]
Maybe we should get the Volvo convertible, it's the best road trip car.

.... As long as the roof doesn't touch.

**Comment by benburkert** [comment]
:+1: sounds good to me. FYI, Enterprise has an Audi A5 convertible: http://exoticcars.enterprise.com/sanfrancisco

dunno if the roof touches though.

**Comment by lstoll** [comment]
@benburkert you interested in a trip?

**Comment by sr** [comment]
@lstoll Return :airplane: is at 2PM, I usually leave the W at 12:15 to catch it with plenty of time. I might be able to change it.

**Comment by lstoll** [comment]
aah, maybe too early then. Be such a rush to try and get back.

**Comment by sr** [comment]
Yeah... flight isn't refundable nor changeable. Fucking Concur, even calling KLM won't do because it's been booked through a third party. I'll be sure to select the flex rate next time. Fuck everything.

**Comment by vinbarnes** [comment]
> Fuck everything.

And often.

**Comment by sr** [comment]
## Monterey

### Dinner
- [Montrio](http://www.montrio.com)

### Breakfast
- http://www.firstawakenings.net
- http://www.katysplacecarmel.com

## Santa Barbara

Wine tour by foot: http://goo.gl/maps/PyJpo

### Dinner
- http://www.bouchonsantabarbara.com/

### Drinks
- [The Neighborhood](http://www.yelp.com/biz/the-neighborhood-santa-barbara) Foosball, billard, ping pong, outside patio
- [Elsie's Tavern](http://www.yelp.com/biz/elsies-tavern-santa-barbara)
  Looks nice and cosy (cash only)
- Dive bars on State Street. Watch out for drunken college students

### Late night food
- [The Blue Owl](http://theblueowlsantabarbara.com/) - Asian american, 2:30am

### Lunch
- [La Super-Rica Taqueri](http://www.yelp.com/biz/la-super-rica-taqueria-santa-barbara) Apparently amazing.
- [Taqueria La Colmena](http://www.yelp.com/biz/taqueria-la-colmena-santa-barbara) Also good in case La Super-Rica is full

**Comment by sr** [comment]
@lstoll Should we book a place in Monterey?

http://www.ichotelsgroup.com/intercontinental/hotels/gb/en/monterey/mryha/hoteldetail

![image](https://f.cloud.github.com/assets/90/56458/b367fe00-5b15-11e2-8756-1edd1459d6ce.jpg)

**Comment by lstoll** [comment]
The fireplace one?

**Comment by lstoll** [comment]
They do have parking, $21. Perfect.

**Comment by sr** [comment]
Haha I am glade you've picked the fireplace one. Forwarded you the confirmation.

**Comment by sr** [comment]
:car::sunglasses::herb::wine_glass::+1:
