### ISSUE TITLE
Restaurant: Maria Bonita

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#2]
Mexican. [https://www.facebook.com/mariabonitaberlin](https://www.facebook.com/mariabonitaberlin) . Because @dylanfm said

@dylanegan @codenamejac

**Comment by DylanFM** [comment]
This is why... puerco especial, or something like that
![Puerco Especial](https://img.skitch.com/20120703-fsjg7c739tkmuifd5dpx84hxw9.preview.jpg)

**Comment by dylanegan** [comment]
![](http://enchulameelperfil.com/images/comentarios/actitud/Puerco%204ever.jpg)

**Comment by lstoll** [comment]
![](http://sharetv.org/images/guide/355983.jpg)

**Comment by lstoll** [comment]
Closing this, because I had about 5,000 Puerco Especial's at Santa Maria.
