### ISSUE TITLE
Eat at Aqua

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#20]
[Aqua](http://www.restaurant-aqua.com), in Wolfsburg - about 1 hour by train from Berlin

"
Chef Sven Elverfeld is billed as a “passionate deconstructionist and re-inventor of plain cuisine”, and a big focus here is the dismantling and reassembling of peasant food. This is highly unorthodox in Germany – most of his peers look to hide the country’s heavy, rather unrefined culinary roots. Elverfeld trained as a confectioner before becoming a chef; his excellent, outlandish desserts would give Willy Wonka a run for his money
"

@dylanegan @sr

**Comment by dylanegan** [comment]
> You know you can quote better than that.

**Comment by lstoll** [comment]
> yeah, but I was lazy.

**Comment by dylanegan** [comment]
Let me do this thing today and figure that stuff out and we'll see.

**Comment by lstoll** [comment]
I actually wanted to do giant dropquotes.

OK cool, not proposing this until post- April anyway - just wanted to have it listed.

**Comment by sr** [comment]
How about February? (dylanegan/travel#59)

**Comment by lstoll** [comment]
I'd be more keen for April/May - I won't be around feb.

**Comment by sr** [comment]
@lstoll When do you get back in the EU again? @dylanegan and I were talking about tentatively meeting up in Hamburg for Acqua then driving down to Krakow for sr/travel#3.

**Comment by lstoll** [comment]
Aqua is closer to Berlin.... I get back the 22nd so I guess I'll just head there a different time.

**Comment by sr** [comment]
> I get back the 22nd so I guess I'll just head there a different time.

Nah dude, I'd rather do it when you can make it :heartbeat:  Just asking

**Comment by dylanegan** [comment]
Let's aim this to be after May and June. With noma and potentially another venture on the cards in June I will probably want to put this in for summer.

**Comment by lstoll** [comment]
Sounds good, it's only a short train from Berlin anyway.

**Comment by lstoll** [comment]
Still want to do this _hint_

**Comment by sr** [comment]
:+1: I'd fly over for that.

**Comment by lstoll** [comment]
November, @dylanegan ?

**Comment by dylanegan** [comment]
@lstoll will know during holiday.

**Comment by lstoll** [comment]
@dylanegan can't figure it any earlier? We have to reserve a couple of months in advance, a bunch of days in November are already booked out.

**Comment by dylanegan** [comment]
What date are you looking at? Mid to late?

**Comment by lstoll** [comment]
Yeah def towards late, probably last week. Early in the week for availability, and hopefully cheaper accommodation.

**Comment by lstoll** [comment]
mmmmmmmmmmmmmm 3:star:

**Comment by sr** [comment]
end of september

**Comment by lstoll** [comment]
if so, we should book soon. availability already dropping…

what dates you gonna be here?

**Comment by sr** [comment]
PollerWiessen (techno boat party in Koln) is on the 28th of September so I am thinking Berlin on Wednesday/Thursday 24/25 for a few nights, Aqua, then train to Koln on Saturday afternoon.

Were you thinking of spending the night in Wolfsburg or training back to Berlin after dinner? I'd love to techno for a night in Berlin if possible.
