### ISSUE TITLE
Housing: Berlin Edition

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#22]
Need somewhere to stay for time in Berlin with @codenamejac. Timing depends a lot on visa requirements.

Also need to work out if it's just us, or @dylanegan as well

**Comment by lstoll** [comment]
So, it's time to get serious about this. @codenamejac 's flight has been booked, and my visa has been approved.

I'm leaning towards two separate places in the same area, rather than a single place. Options are better that way.

The place @dylanegan and I looked at is still available, and I think the price has dropped a little too. Otherwise, there's a bunch of stuff on there.

I'm thinking 23 April until 23 August - 4 months even. Beyond that, I'd extend or just rent a place properly and furnish it with all

![](http://www.globalinternships.se/wp-content/uploads/2012/10/ikea-logo.jpg)

**Comment by lstoll** [comment]
Oh, the links to those places we looked at:

(the one I want to get:) https://www.airbnb.com.au/rooms/743622
(the side by side rooftop ones): https://www.airbnb.com.au/rooms/742127 &  https://www.airbnb.com.au/rooms/743648
(balcony): https://www.airbnb.com.au/rooms/742058
('loft' w/ single beds): https://www.airbnb.com.au/rooms/742691  &  https://www.airbnb.com.au/rooms/742757
(studio w/single): https://www.airbnb.com.au/rooms/742728

I actually think all the singles and doubles are the same, just not pushed together.

Important Directions to [Dirty South](https://maps.google.com/maps?saddr=Koppenstra%C3%9Fe+29A,+10243+Berlin,+Germany&daddr=Krossener+Str.+18,+Berlin,+DE.&hl=en&ie=UTF8&sll=52.500549,13.424091&sspn=0.087675,0.20771&geocode=FUBVIQMdKgjNAClvnhJrQE6oRzHYDgBGAHoMrA%3BFRg_IQMdOVvNACkvKAjGXk6oRzFU9S7dSYw9CQ&dirflg=w&mra=ls&t=m&z=16)

Also 43 mins Door-to-Door to Green Door, and about ~15 walk to the tram station for Filetstück - unless we went via Alex.

**Comment by dylanegan** [comment]
DAMN YOU HOUSING THAT ISN'T LIKE OUR FIRST PLACE!

**Comment by lstoll** [comment]
DAMNIT

![](http://newton64.ca/images/animazing/ShakeHarderBoy.gif)

**Comment by ghost** [comment]
IT'S A CONSPIRACY

**Comment by lstoll** [comment]
[AirBnB places](https://www.airbnb.com.au/s/Berlin?checkin=22-04-2013&checkout=22-09-2013&guests=3&room_types%5B%5D=Entire+home%2Fapt&hosting_amenities%5B%5D=4&min_bedrooms=2&price_max=2400)

[@roidrage 's place](http://www.immobilienscout24.de/expose/68356768)

Suitible places on crocodilian:
[F'hain](http://www.rooms-in-berlin.com/8176.html)
[Mitte](http://www.rooms-in-berlin.com/6864.html)
[Tiergarten](http://www.rooms-in-berlin.com/8752.html)

I pretty much need to book something by next week, even if only for 2-3 months.

@roidrage - how long do you think the minimum lease period would be on your old place?

**Comment by roidrage** [comment]
I'm not sure there's a minimum lease, but having you in there for just 2-3 months is sure to make them unhappy.

**Comment by lstoll** [comment]
Oh of course, I'd be thinking 1yr minimum. I just know long term stuff can be a thing in .de

**Comment by lstoll** [comment]
Couldn't wait any longer, so I sent a booking request [the airbnb I liked](https://www.airbnb.com.au/rooms/743622) for the 8 days in Berlin, before Tuscany. Also got a hotel for GitMerge / between Tuscany and Copenhagen.

That pushes the date back for a 'proper' apartment until about 16th May.

**Comment by lstoll** [comment]
Looks like I left it too late - seems like that whole building is booked out for that period. Looking at other options...

**Comment by dylanegan** [comment]
Sorry, been a bit slack on this. I'm back this weekend if we need anything scoped out.

**Comment by lstoll** [comment]
ref dylanegan/berlin#7 dylanegan/berlin#8

**Comment by lstoll** [comment]
Have a real house now, all good.

**Comment by roidrage** [comment]
Pictures and a barbie, or it didn't happen!
