### ISSUE TITLE
Tuscany

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#24]
For GitHub Destination. Gotta get @codenamejac and I there.

Leave on 30 Apr, return 8 May?

sr/travel#2

**Comment by lstoll** [comment]
Plan now is to arrive 30th, leave 7th. Stay at the conf hotel 7-9 (GH has the booking from 9-12th)

Flights

![airberlin - Flights to Berlin and Dusseldorf airberlin com - airberlin com 2013-04-01 17-08-14](https://f.cloud.github.com/assets/694/323042/851c02dc-9a92-11e2-8928-687161784c57.png)

![easyJet - Step 1 - Flights 2013-04-01 17-10-26](https://f.cloud.github.com/assets/694/323047/d3527558-9a92-11e2-94fe-7eff49aad888.png)

Car rental: 

![Book and pay 2013-04-01 17-24-33](https://f.cloud.github.com/assets/694/323071/cd2f3a06-9a94-11e2-886b-5e6df70ffd3e.png)

Drive to house:

![Malpensa Airport to Localit Bellavista Bellavista AR Italy - Google Maps 2013-04-01 17-13-46](https://f.cloud.github.com/assets/694/323050/4afb8a36-9a93-11e2-8472-8570c6dd4999.png)

**Comment by lstoll** [comment]
Note - AirBerlin flights are from Tegel.

**Comment by lstoll** [comment]
On return, stay at Ramada - [much cheaper](http://www.booking.com/hotel/de/ramada-berlin-alexanderplatz.en-gb.html?aid=356980;label=gog235jc-hotel-en-de-radissonNsasNberlin-unspec-au-com;sid=96ea1120bcb581067b5d485462d40924;dcid=1;checkin=2013-05-07;checkout=2013-05-09;srfid=6618df8134332da336b35a4399f0ed5cd2376a0aX4)

**Comment by sr** [comment]
Snow chains what?

**Comment by lstoll** [comment]
@sr lrn2web - it's an optional extra, that I haven't checked :)

**Comment by lstoll** [comment]
:airplane: booked.

![airberlin - Flights to Berlin and Dusseldorf airberlin com - airberlin com 2013-04-01 19-52-24](https://f.cloud.github.com/assets/694/323274/73d01934-9aa9-11e2-8600-dd878486a05f.png)

**Comment by lstoll** [comment]
:car: booked.

![Confirmation reservation 2013-04-01 20-47-04](https://f.cloud.github.com/assets/694/323395/16c5e1e4-9ab1-11e2-99c4-81dd45196be4.png)

**Comment by lstoll** [comment]
:hotel: booked for Berlin return. Ramada from 7th -> 9th, then the conference hotel. Will be around the 8th to help @thedukeofsf get conf set up.
