### ISSUE TITLE
Noma / Denmark

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#26]
Gotta go to dat noma with @dylanegan :heart:

/cc @codenamejac

**Comment by lstoll** [comment]
@dylanegan do you have flights/accom/etc yet? I'm planning on leaving the 12th for copenhagen, returning 15th?

**Comment by lstoll** [comment]
@sr @thedukeofsf how are you guys getting up there?

**Comment by sr** [comment]
@dylanegan and myself where talking about driving up there from Berlin. I'll already have a car. See dylanegan/travel#72

**Comment by jeniferduke** [comment]
@lstoll - your dinner reservation is on the 15th, so how are you planning on returning on the 15th? 

I'll be heading to CPH on 5/13. Will be taking either easyjet or air berlin. Probably staying till the 15th or 16th, but could stay until the 18th. I just need to get to Paris on the 18th.

**Comment by lstoll** [comment]
I couldn't remember the exact night, but that makes sense. So I guess leave on the 16th.

Might fly to CPH on the 13th as well, prices on the 12th are crazy. Or maybe just drive up, will figure that out this week.

**Comment by dylanegan** [comment]
@lstoll the drive is about 6 hours according to Google. That includes a [ferry](http://www.scandlines.com/tickets-and-prices/tickets-and-prices/rostock-gedser).

**Comment by lstoll** [comment]
@dylanegan oh shit, that's an easy drive then. Just gotta see how much a weeks car rental is, but shouldn't be too bad.

**Comment by sr** [comment]
@lstoll Get a convertible then we can all :soccer: out of control and maybe :boom: on the highway with the roofs down like this guy :horse_racing: 

![](http://www.examiner.com/images/blog/wysiwyg/image/399px-Modern-Knight.jpg)

**Comment by lstoll** [comment]
Holy shit, convertible jousting would be awesome.

**Comment by dylanegan** [comment]
![](http://www.viceland.com/wp/wp-content/uploads/2011/05/img_2.jpeg)

**Comment by lstoll** [comment]
This was T A S T Y.

Also, convertible jousting is for another time.
