### ISSUE TITLE
Nordic Ruby

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#27]
Need to get there. Accom provided Jun 6-9th

**Comment by lstoll** [comment]
Check in 1600 Jun 9th, 1200 Jun 9th

**Comment by lstoll** [comment]
@dylanegan are you going?

**Comment by lstoll** [comment]
![airberlin - Flights to Berlin and Dusseldorf airberlin com - airberlin com 2013-04-01 18-19-09](https://f.cloud.github.com/assets/694/323147/6cc20c5e-9a9c-11e2-958f-779009979104.png)

**Comment by dylanegan** [comment]
@lstoll yeah. On the 6th you need to make your own way to the venue. The ferry will be best from Stockholm if you want to spend some time in town before heading to the venue. On the way out a taxi from Yasuragi to the airport is best.

**Comment by lstoll** [comment]
All booked, [in TripIt](https://www.tripit.com/trip/public/id/94B691F1F3ED). Leave Berlin on the 5th, spend a night in stockholm, then conf.

**Comment by lstoll** [comment]
:ship: 'd an amazing time.
