### ISSUE TITLE
Summer S U M M I T adventure.

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#29]
Summit will be over 2/8, fly evening of 6/8.

What do?

/cc @sr

**Comment by lstoll** [comment]
Options I can think of so far are:

1) Still go to LA. Stay at a hotel near venice. Like [Hotel Erwin](http://www.hotelerwin.com)
2) Go to Palm springs, chill the fuck out at a resort.
3) L A S V E G A S.

**Comment by sr** [comment]
Definitely leaning towards chilling the fuck out. Hotel Erwin actually sounds really appealing because beach and roof top while still being in the city-ish so we still have the option to do stuff.

**Comment by sr** [comment]
What dates were you thinking btw?

**Comment by lstoll** [comment]
I guess Fri and Sat nights at least, Maybe Sun. Be nice to have Mon/Mon night/Tues in SF to see people.

And Erwin is looking like a pretty winning option. @rtomayko you stayed there yeah? Was it good?

**Comment by lstoll** [comment]
God we nailed this in Palm Springs.
