### ISSUE TITLE
Prague

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#3]
Do we want to look in to Prague this weekend?

@codenamejac @dylanegan

**Comment by lstoll** [comment]
Ok, I had a quick look. I think leaving Saturday, returning Monday is better - accommodation will be cheaper and it will be a bit quieter.

## Accommodation

A nice hostel I know, [Miss Sophies](http://www.miss-sophies.com/) has private rooms (incl. Bathroom) for CZK1,936 on Sat, and  CZK1,554 on Sun (Approx €76 and €61). Availability is low, so we'd need to get on to this.

## Transport

### Train

Depart 0845 Sat, Arrive Prag 1326. €132 for 3 people.
Depart 1429 Mon, Arriver Berlin 1913. €249 for 3 peopl

So €127p/p

### Drive

Renting a car is €90,70. Google estimates 3hr45 - 4hr driving time, 355km. I estimate €110 for fuel, and €40-60 for secure parking. So approx €86, pp.

Thoughts?

**Comment by janaboruta** [comment]
Cafe Lounge
Address: Plaska 615/8 150 00 Praha 5- Mala Strana
Reason: Best food and coffee I had the entire trip I was in Europe
Website: http://www.cafe-lounge.cz/

River Lounge
Corey and I were walking around the city and we randomly found this cafe and wine bar. They had the best outdoor seating area. We were sitting outside with the Charles Bridge about 100 feet from us. It was beautiful!
If you like white wine try Francois Lurton Sauvignon Blanc. 
Address: Cihelna 2b, Prague 11800, Czech Republic

**Comment by janaboruta** [comment]
This airbnb apartment was also fantastic. About a 15 to 20 minute walk from everything. ALl three of you guys could stay in the apartment. http://www.airbnb.com/rooms/117451

If you want to be in the heart of everything I recommend the Three Storks hotel. It's right underneath the Praha Castle. Rooms are about $152 a night. http://www.splendia.com/en/hotel/?hotel_id=30558&datestart=15/08/12&dateend=16/08/12

**Comment by DylanFM** [comment]
Stayed here which was nice, they even gave Bel a letter opener for her birthday o-O http://www.mamaison.com/prague-pachtuv-palace-prague.html

**Comment by lstoll** [comment]
@janaboruta awesome, thanks! Sadly, that hotel is out of our budget, we're 66.6% unemployed ;)

@codenamejac @dylanegan hostel booked, miss sophies:

![](http://sk.lds.li/Melounova_3%2C_prague_-_Google_Maps-20120705-000328.jpg)
![](http://sk.lds.li/Inbox_%2840262_messages%2C_53_unread%29-20120705-000430.jpg)

It's easily walkable to the places we want to go, and key public transport nearby.

Also, car is a Golf VI, Diesel requested.

![](http://sk.lds.li/MyEC_My_Bookings_Existing_Bookings-20120705-003758.jpg)

Rental conditions that say we can drive the car in the Czech Republic: [here](http://www.europcar.de/EBE/module/render/General-Conditions) 

Now we just need to do this:

![](http://sk.lds.li/Sophienstra%C3%9Fe_16%2C_10178_Berlin%2C_Germany_to_Miss_Sophie_s_-_Google_Maps-20120705-003906.jpg)

**Comment by DylanFM** [comment]
_Never mind me while I pine for Prague road trips, carry on._

**Comment by dylanegan** [comment]
@janaboruta is http://www.kampagroup.com/en/restaurant.php?rid=1 the river lounge?

**Comment by dylanegan** [comment]
NAILED [IT](https://github.com/dylanegan/travel/blob/master/Czech%20Republic/Praha.md)!

**Comment by lstoll** [comment]
Yeahh!!!

Closing.
