### ISSUE TITLE
MiniSummit in SF + Other Adventure.

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#30]
Gotta be in SF 6/7/8 Nov. ~~Should stay the weekend after, 'Football' with @wfarr sounds fun.~~

~~Then should do a mini-adventure while in the US. Maybe Chicago, and then family in O H I O.~~

Weekend of arrival is rented C class to drive somewhere (TBD), then afterwards probably Vancouver.

**Comment by lstoll** [comment]
/cc @dgoodlad

I can change my return flight for $330 to depart YVR at 2045 on Wed, 13th Nov. Will probably fly up from SF on Sat, 9th.

@dgoodlad - what do you think the chances are of you being there? I should probably make this change soon.

**Comment by dgoodlad** [comment]
@lstoll let's say 80% right now; need to confirm what flights I can push for before I officially start. I suspect MEL-SFO return is similar pricing to MEL-YVR, SFO-MEL, so shouldn't be an issue though.

**Comment by lstoll** [comment]
Sweet, I might just :ship: it then. Worst case, I still get to hang out in Van.

If you do head up, when would you expect to arrive?

**Comment by dgoodlad** [comment]
I'd plan to arrive either Friday or Saturday.

**Comment by dgoodlad** [comment]
@lstoll just submitted my plans to the travel agent; would arrive in YVR on Friday Nov 8 around mid-day.

**Comment by dgoodlad** [comment]
@lstoll wdyt about https://www.airbnb.com.au/rooms/1495324

**Comment by lstoll** [comment]
lgtm :shipit:

**Comment by lstoll** [comment]
WE DID THIS
