### ISSUE TITLE
Atlanta

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#31]
For DevopsDays Atlanta.

Probably fly in Oct 1, and leave Oct 6 or 7.

Stay at one of the W's in town. @wfarr, which one was it?

/cc @wfarr @jnewland.

**Comment by lstoll** [comment]
Probably flight.

![2013-09-10 at 12 15 am](https://f.cloud.github.com/assets/694/1110947/69e05722-199d-11e3-9db7-d5dbb597ff4a.png)

**Comment by wfarr** [comment]
W Midtown Atlanta. The one at 14th and Juniper.

**Comment by lstoll** [comment]
@wfarr :cool:, what dates are you going to be in town?

**Comment by lstoll** [comment]
Probable hotel

![2013-09-10 at 12 20 am](https://f.cloud.github.com/assets/694/1110972/21cbc1b4-199e-11e3-9b7e-7d01d1895678.png)

**Comment by wfarr** [comment]
If your flights are confirmed, I'll book my own travel and lodging this week then.

**Comment by lstoll** [comment]
Booked. Arrive Oct 1, Leave Oct 7, Stay at W Midtown. Details in TripIt.

**Comment by lstoll** [comment]
WE DID THIS!
