### ISSUE TITLE
Amsterdam

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#32]
Visit http://www.marzee.nl/galerie/contact/, check it out, Drop Ben&Abby off at FRA.

/cc @benschwarz @codenamejac

**Comment by lstoll** [comment]
Probably drive to Amsterdam on Wednesday, spend Wed and Thurs night there. Drive to the Gallery on Fri, check it, then to Frankfurt Airport Friday evening. Stay there, B&A Fly out. Maybe train back to Berlin? Want to visit anything while over that way?

**Comment by lstoll** [comment]
Mercure FRA, €63/night.

**Comment by benschwarz** [comment]
:hotel: Mercure FRA, booked

**Comment by lstoll** [comment]
AirBnB:

https://www.airbnb.com/rooms/358155

Hotel:

http://www.booking.com/hotel/nl/conscious-vondelpark.en-gb.html?sid=275db527ad396605521373c55604dca0;dcid=1;checkin=2013-09-25;checkout=2013-09-27;group_adults=2;group_children=0;group_adults=2;group_children=0;group_rooms=25418702_80312459_0_42_2_0_0,25418702_80312459_0_42_2_0_0;srfid=39d48ed501769ff99f4de82097bd1985ec84fdf6X6

Not a crazy amount of stuff available by the looks. Wanna check around?

**Comment by lstoll** [comment]
AirBnB Booked. and everything else.

Now what do. @dylanegan, recommendations?

**Comment by dylanegan** [comment]
So much.

**Comment by lstoll** [comment]
Danke vielmals

**Comment by dylanegan** [comment]
[Amsterdam](https://github.com/dylanegan/travel/blob/master/Netherlands/Amsterdam.md).

**Comment by lstoll** [comment]
NAILED.
