### ISSUE TITLE
Fingal Hack House

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#34]
Wanna do this again next year. Looking at either the beginning, or end of Feb. This time, probably partners welcome and a little more social - rather than trying to be an 'official' GitHub deal.

![2013-09-30 at 1 08 pm](https://f.cloud.github.com/assets/694/1236448/df48e3e8-29c0-11e3-8f4f-a661de8d999e.png)

![2013-09-30 at 1 11 pm](https://f.cloud.github.com/assets/694/1236450/fc4a3a5a-29c0-11e3-91ba-1f681a01796a.png)

/cc @dgoodlad @benschwarz @rodjek @wfarr @benburkert #33

**Comment by wfarr** [comment]
> ![](https://f.cloud.github.com/assets/694/1236448/df48e3e8-29c0-11e3-8f4f-a661de8d999e.png)

If you aren't drowning, you're not deep enough.
