### ISSUE TITLE
Melbourne

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#36]
Probably 8-15 Feb.

AirBnB Fitz/Collingwood/etc.

/cc @codenamejac

**Comment by lstoll** [comment]
Love this place: https://www.airbnb.com/rooms/256186

![2013-10-09 at 11 39 pm](https://f.cloud.github.com/assets/694/1301981/46abbc24-312b-11e3-9b36-c01701da8f5f.png)

**Comment by lstoll** [comment]
Booked, gonna be in Collingwood from 7-15 Feb.

Be prepared, @benschwarz @dgoodlad @quamen @geelen @joho @alanjrogers @charliesome

**Comment by joho** [comment]
Poo. I'll be in NZ for family duties then webstock.

**Comment by quamen** [comment]
Shawesome! See you then.
