### ISSUE TITLE
Ben Schwarz in EU (and others)

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#37]
So Mr. @benschwarz will be here. And some others.

Been talking about doing some kind of adventure in EU, maybe Spain/France or something else Rad.

What dates should we look at shit for? When is the conf and shit?

/cc @dylanegan

**Comment by benschwarz** [comment]
Dates are: 
- Arrive on the 3rd (7:45pm)
- 5th—7th Berlin Festival

7—12th ADVENTURE TIME
- 12th CSSConf 
- 13th—14th JSConf
- 19th Fly to Australia

**Comment by dylanegan** [comment]
@benschwarz :beers: :beers:.

**Comment by dylanegan** [comment]
:cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail: :cocktail:

**Comment by dylanegan** [comment]
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:
