### ISSUE TITLE
Switzerland/Zürich roadtrip

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#4]
Better start thinking about this...

@dylanegan @codenamejac

**Comment by lstoll** [comment]
Once we confirm when we get to look at the apartment, I'll start planning this more.

**Comment by lstoll** [comment]
Deferred until return - between 6 aug and xx?

**Comment by lstoll** [comment]
So, my Visa appt. is 13 Aug, and we move in/your visa appointments 21 Aug. Between then?

**Comment by dylanegan** [comment]
@lstoll yeah, I am also thinking of hitting up [Montpellier](https://github.com/dylanegan/travel/issues/14).

**Comment by lstoll** [comment]
In conjunction with, or instead? We may be able to drive down, or drop you off in Genf - [train should be easy from there](http://tgv.tgv-europe.ch/de/tgv-genf-mittelmeer).

**Comment by lstoll** [comment]
Superseded by #12
