### ISSUE TITLE
Berlin Apartment

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#5]
Need somewhere permanent to stay.

@codenamejac @dylanegan

**Comment by lstoll** [comment]
Currently talking to the landlord of [that one we liked originally](http://www.city-wohnen.de/berlin/26243/9). It's €1800 for 3 people, available approx 20 August. Hopefully we can inspect it this Friday, Saturday or Sunday. I suggested we'd be there until end of Jan.

**Comment by lstoll** [comment]
Crocodilian suggested [an apartment in Krezberg](http://www.rooms-in-berlin.com/7708-apartment-berlin.html). It's still on the more expensive side of things (€1700), and the second bedroom only has a single bed. However it is available earlier (20 Jul onwards).

I'm not sure the location is that accessible though.

**Comment by lstoll** [comment]
The alternate is two separate one bedroom apartments in a similar area. There definitely seems to be much more available here. Thoughts?

**Comment by lstoll** [comment]
@codenamejac just found this one: [http://www.city-wohnen.de/eng/berlin/flat-search/details/?a_nr=30835&b_nr=1](http://www.city-wohnen.de/eng/berlin/flat-search/details/?a_nr=30835&b_nr=1)

It's near Frankfurter Tor. Looks nice and spacious, and a bit cheaper. Should we check it out?

**Comment by lstoll** [comment]
Looks like the awesome one is all good. Meeting at 1600 20.Jul to finalize. All documents needed collected, will close when it's booked.

**Comment by dylanegan** [comment]
@lstoll good luck. Also thanks and FUCK YEAH!

**Comment by dylanegan** [comment]
:rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow: :rainbow:

**Comment by lstoll** [comment]
So nailed the apartment.
