### ISSUE TITLE
München

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#7]
We need to have a decent trip to Munich. @dylanegan and @codenamejac are a given, pretty sure @sr is in too.

**Comment by sr** [comment]
Yup, I'm in. :+1:

**Comment by sr** [comment]
Is @codenamejac Jacqui?

**Comment by lstoll** [comment]
@sr: yep.

**Comment by sr** [comment]
http://harrykleinclub.de/

Apparently really nice intimate house club. Residents sound nice: http://harrykleinclub.de/ohr/content.php

Source: http://nightclubber.ro/vera-tini-at-harry-klein-club-munchen-30-11-2007-7-hour-set

**Comment by lstoll** [comment]
Kind of superseded by #12 . Will keep this open though, I still think we should hang down there.

**Comment by lstoll** [comment]
Closing this for now. We can München whenever.
