### ISSUE TITLE
Dos Palillos Lunch

### ISSUE THREAD

**Issue by lstoll** [lstoll/travel#8]
Should we organize a big (€20ish) lunch here, maybe Thursday this week? Who would come?

/cc @codenamejac @dylanegan @sr @danishkhan @jeshuaborges @brianmario

**Comment by brianmario** [comment]
just so it's known, I had my brains blown out by dinner here tonight.

**Comment by lstoll** [comment]
So, @kneath @mtodd @nrrrdcore @rseinham @billyroh @jcostello @tmm1 ? Need to know by this afternoon.

**Comment by mtodd** [comment]
I'm down!

**Comment by kneath** [comment]
I'm in

**Comment by nrrrdcore** [comment]
I'm in.

**Comment by dylanegan** [comment]
I DEMAND A RECOUNT!

**Comment by dylanegan** [comment]
http://www.youtube.com/watch?v=7QLSRMoKKS0

**Comment by lstoll** [comment]
Oh, need to include @roidrage !

**Comment by kneath** [comment]
Oh, also it's @rsanheim

**Comment by roidrage** [comment]
Afraid I won't make it for lunch tomorrow.

**Comment by tmm1** [comment]
I'm in.

**Comment by sr** [comment]
:+1:

**Comment by rsanheim** [comment]
I am not in, as I fly out thursday morning :(

**Comment by nrrrdcore** [comment]
@lstoll What time are we lunching?

**Comment by danishkhan** [comment]
I'm in

**Comment by lstoll** [comment]
I'd say 1300, will confirm in a few hours.

**Comment by lstoll** [comment]
Table booked for 1300 tomorrow (Thurs 12.Jul). See you there.

**Comment by sr** [comment]
:sparkles:

**Comment by dylanegan** [comment]
YO BITCHES, ARE YOU READY FOR LUNCH?

![](http://i.imgur.com/c0UQa.gif)

![](http://i.imgur.com/UnxQ2.gif)

**Comment by sr** [comment]
YES I AM WAITING IN LINE FOR THE SHOWER

**Comment by vmg** [comment]
IS IT TOO LATE TO SAY IM IN FUCK

**Comment by dylanegan** [comment]
The shower line ride is the best ride.

![](http://gifs.gifbin.com/022010/1266318430_serious_treadmill_pwnage.gif)

**Comment by lstoll** [comment]
@tanoku you might be lucky. Pretty sure we have a full table, but they might be able to do another one. Can't say for sure though.
